### ISSUE TITLE
Deprecated Constant ENERGY_KILO_WATT_HOUR

### ISSUE THREAD

**Issue by timwelchnz** [codyc1515/ha-contact-energy#6]
Hi there,

Thanks for your efforts in getting this add-on up and running. Thought I'd log this as an issue while I try to resolve the other problems I seem to be having with it.
 
`2024-01-29 20:11:17.857 WARNING (MainThread) [homeassistant.const] ENERGY_KILO_WATT_HOUR was used from contact_energy, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/codyc15/ha-contact-energy/issues`

Obviously doesn't affect anyone till 2025.1 but you know... may as well get it logged.

**Comment by codyc1515** [comment]
To be honest, there should be no constants as we should not even need the usage sensor. It is just a dummy sensor so that we can perform the automatic updates. I made this integration well before I knew good HA coding practises, so it's probably due for a rewrite anyway. Thanks for the report.
